apidrf/urls.py
from django.urls import include, path

from rest_framework.routers import DefaultRouter

from apidrf import views


router = DefaultRouter()
router.register(r'notes', views.NoteViewSet, basename='note')
router.register(r'users', views.UserViewSet, basename='user')


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
]

mynotes/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
    path('apidrf/', include('apidrf.urls')),
]

notes/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, re_path
from . import views

app_name = 'notes'
urlpatterns = [
    path('', views.home, name="home"),
    path('notes/', views.IndexView.as_view(), name="index"),
    re_path('notes/(?:(?P<status>[a-zA-Z]+))?/$', views.IndexView.as_view(), name="index_archived"),  # Optional kwarg
    path('notes/<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('notes/<int:note_id>/update/', views.update, name="update"),
    path('notes/create/', views.create, name="create"),
    path('note/create/', views.NoteCreateView.as_view(), name="note-create"),
    path('note/<int:pk>/', views.NoteUpdateView.as_view(), name="note-update"),
    
    # Move auth urls to another app?
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page='notes:login'), name="logout"),
]

apidrf/models.py
from django.db import models

# Create your models here.

notes/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Note(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField("Description")
    create_date = models.DateTimeField(auto_now_add=True)
    last_modified_date = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("notes:note-update", kwargs={"pk": self.pk})

notes/forms.py
from django import forms

from .models import Note


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'description', 'is_active']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }

apidrf/views.py
from django.contrib.auth.models import User

from rest_framework import permissions, viewsets

from apidrf.permissions import IsCreatedBy
from apidrf.serializers import NoteSerializer, UserSerializer
from notes.models import Note


class NoteViewSet(viewsets.ModelViewSet):
    """
    This viewset provides list, create, retrieve, update and delete operations.
    """

    queryset = Note.objects.all()
    serializer_class = NoteSerializer
    permission_classes = [permissions.IsAuthenticated, IsCreatedBy]

    def perform_create(self, serializer):
        self.set_created_by(serializer)
    
    def set_created_by(self, serializer):
        """Set created_by field using logged in user."""
        serializer.save(created_by=self.request.user)

    def get_queryset(self):
        """
        Be careful, this overrided method is shared by all actions (list, retrieve, update, etc)
        It can yield weird (different) outcomes than expected. For example:
        
        Raise 404 status code rather than 403.
        """
        filtered_notes = Note.objects.filter(created_by=self.request.user)
        return filtered_notes.order_by('-last_modified_date')


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    """This viewset provides list and retrieve actions."""
    queryset = User.objects.all()
    serializer_class = UserSerializer

notes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import NoteForm
from .models import Note


def home(request):
    return HttpResponseRedirect(reverse('notes:login'))


class IndexView(LoginRequiredMixin, generic.ListView):
    context_object_name = 'notes'
    template_name = 'notes/index.html'

    def get_queryset(self):
        active_status = True
        kw_status = self.kwargs.get('status')
        if kw_status and kw_status == 'archived':
            active_status = False
        active_user_notes = Note.objects.filter(is_active=active_status, created_by=self.request.user)
        ordered_notes = active_user_notes.order_by('-last_modified_date')
        return ordered_notes

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_input = self.request.GET.get('search_input', '')
        context['search_input'] = search_input
        # This works becase get_queryset() is executed before get_context_data()
        context['notes'] = context['notes'].filter(title__icontains=search_input)
        return context


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Note
    template_name = 'notes/detail.html'
    login_url = reverse_lazy('notes:login')


def update(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    note.title = request.POST.get('title') or note.title
    note.description = request.POST.get('description') or note.description
    note.save()
    return HttpResponseRedirect(reverse('notes:detail', args=(note.id,)))

def create(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save()
            return HttpResponseRedirect(reverse('notes:detail', args=(note.id,)))
    else:
        form = NoteForm()
    return render(request, 'notes/create.html', {'form': form})



## Form handling with class-based views

class NoteCreateView(LoginRequiredMixin, CreateView):
    model = Note
    form_class = NoteForm
    template_name = 'notes/create.html'

    def form_valid(self, form):
        """
        Override this method in order to set the logged user to the instance related to the form.
        This instance is the object (Note) that will be saved using the form data.
        """
        form.instance.created_by = self.request.user
        form.instance.is_active = True  # El default True dejó de funcionar desde que agregue el 'created_by'
        return super(NoteCreateView, self).form_valid(form)
    

class NoteUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Note
    form_class = NoteForm
    template_name = 'notes/detail.html'

    def test_func(self):
        """Check if the current object (Note) was created by the logged user."""
        logged_user = self.request.user
        current_note = self.get_object()
        return current_note.created_by == logged_user




## Handling authentication (Move it to another app?)
class CustomLoginView(LoginView):
    template_name = 'registration/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        next_url = self.request.POST.get('next', )
        if next_url:
            return next_url
        return reverse_lazy('notes:index')
## 

notes/templates/notes/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% load static %}
        <link rel="stylesheet" href="{% static 'notes/style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <title>{% block title %}Base{% endblock %}</title>
    </head>
    <body>
        {% block header %}
            <header class="navbar navbar-expand-lg bg-body-tertiary sticky-top"> <!-- class="custom-header" -->
                <div class="container-fluid mx-4"> <!-- custom-navbar -->
                    <a class="custom-a-link" href="{% url 'notes:index' %}" style="text-align: center">
                        <h1>Notes</h1>
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse custom-navbar" id="navbarSupportedContent">
                        {% if user.is_authenticated %}
                            <a href="{% url 'notes:note-create' %}"><span>Create note</span></a>
                            <a href="{% url 'notes:index_archived' status='archived' %}">
                                <span>Archived notes</span>
                            </a>
                            <span>Hi, {{ user.username }}</span>
                            <form action="{% url 'notes:logout' %}" method="post">
                                {% csrf_token %}
                                <button class="btn p-0" type="submit"><span><strong>Logout</strong></span></button>
                            </form>
                        {% else %}
                            <a href="{% url 'notes:login' %}"><span><strong>Login</strong></span></a>
                        {% endif %}
                        <div>
                        </div>
                    </div>
                </div>
            </header>
        {% endblock %}
        <div class="container mt-4">
            {% block 'content' %}
            {% endblock %}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        </div>
    </body>
</html>

notes/templates/notes/create.html
{% extends 'notes/base.html' %}
{% block title %}Create note{% endblock %}
{% block 'content' %}
<form action="{% url 'notes:note-create' %}" method="post">
    {% csrf_token %}
    <fieldset class="custom-fieldset">
        <legend class="custom-legend p-2"><h2>Create</h2></legend>
        {% csrf_token %}
        
        {{ form.non_field_errors }}
        <div class="fieldWrapper mb-3">
            {{ form.title.as_field_group }}
        </div>
        <div class="form-group mb-3">
            {{ form.description.as_field_group }}
        </div>

        <input type="submit" value="Create">
    </fieldset>
</form>
{% endblock %}

notes/templates/notes/detail.html
{% extends 'notes/base.html' %}
{% block title %}Detail note{% endblock %}
{% block 'content' %}
<form action="{% url 'notes:note-update' note.id %}" method="post">
    {% csrf_token %}
    <fieldset class="custom-fieldset">
        <legend class="custom-legend p-2"><h2>Detail</h2></legend>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {{ form.non_field_errors }}
        <div class="fieldWrapper mb-3">
            {{ form.title.as_field_group }}
        </div>
        <div class="form-group mb-3">
            {{ form.description.as_field_group }}
        </div>
        <label for="title">Status</label><br>
        <div class="form-check form-switch mb-4">
            <input class="form-check-input" type="checkbox" role="switch" id="is_active" name="is_active"
                   {% if note.is_active %} checked {% endif %}>
            <label class="form-check-label" for="is_active"></label>
        </div>
        <input type="submit" value="Update">
    </fieldset>
</form>
<h5>Last modified at: {{ note.last_modified_date }}</h5>
<h5>Created at: {{ note.create_date }}</h5>
{% endblock %}

notes/templates/notes/index.html
{% extends 'notes/base.html' %}
{% block title %}
    {% if 'archived' in request.path %}
        Archived notes
    {% else %}
        Notes
    {% endif %}
{% endblock %}
{% block 'content' %}
    <main>
        <div class="my-3">
            {% if 'archived' in request.path %}
                <form action="{% url 'notes:index_archived' status='archived' %}" method="get">
            {% else %}
                <form action="{% url 'notes:index' %}" method="get">
            {% endif %}
                <div class="d-flex gap-2">
                    <input class="form-control" type="search" name="search_input" value="{{ search_input }}">
                    <input class="" type="submit" value="Search">
                </div>
            </form>
        </div>
        {% if notes %}
            <div class="list-notes">
                {% for note in notes %}
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a class="custom-a-link stretched-link" href="{% url 'notes:note-update' note.id %}">{{ note.title }}</a>
                            </h5>
                            <p class="card-note-description">{{ note.description }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No notes to show</p>
        {% endif %}
    </main>
{% endblock %}